name: build image
on:
  push:
    branches: [ web ]

permissions:
  contents: read
  packages: write

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:

      - name: Checkout del codigo
        uses: actions/checkout@v5

      - name: Login a github packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}/web_app:latest