name: hello world
on: [workflow_dispatch]
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - run: python3 main.py

    - name: crear clave ssh
      env:
        ssh_key: $ {{ secrets.SSh_KEY}}
      run:
        echo "$ssh_key" > key.pem
        chmod 600 key.pem
    
    - run: ls -la

    - run: cat key.pem